### ISSUE TITLE
Html is too long! this will crash the client!

### ISSUE THREAD

**Issue by dEROZA** [HorridoJoho/YANModPack#2]
[13/02 10:49:01] Html is too long! this will crash the client!
java.lang.Throwable
        at com.l2jserver.gameserver.network.serverpackets.AbstractHtmlPacket.setHtml(AbstractHtmlPacket.java:80)
        at com.l2jserver.gameserver.network.serverpackets.AbstractHtmlPacket.<init>(AbstractHtmlPacket.java:68)
        at com.l2jserver.gameserver.network.serverpackets.NpcHtmlMessage.<init>(NpcHtmlMessage.java:50)
        at YANModPack.YANBuffer.YANBuffer._showAdvancedHtml(YANBuffer.java:200)
        at YANModPack.YANBuffer.YANBuffer._htmlShowUnique(YANBuffer.java:278)
        at YANModPack.YANBuffer.YANBuffer._executeHtmlCommand(YANBuffer.java:308)
        at YANModPack.YANBuffer.YANBuffer.executeCommand(YANBuffer.java:761)
        at YANModPack.YANBuffer.YANBufferVoicedCommandHandler.useVoicedCommand(YANBufferVoicedCommandHandler.java:51)
        at handlers.bypasshandlers.VoiceCommand.useBypass(VoiceCommand.java:61)
        at com.l2jserver.gameserver.network.clientpackets.RequestBypassToServer.runImpl(RequestBypassToServer.java:347)
        at com.l2jserver.gameserver.network.clientpackets.L2GameClientPacket.run(L2GameClientPacket.java:70)
        at com.l2jserver.gameserver.network.L2GameClient.run(L2GameClient.java:1134)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

**Comment by HorridoJoho** [comment]
How many skills are on the unique bufflist?
Are you using a modified unique.html?

**Comment by dEROZA** [comment]
No, unique is a default. I used more than standart count of skills. Can you great a pagination for solved this error? Thx.

**Comment by HorridoJoho** [comment]
Shortcut commands were added with the latest changes. This possibly resolves that issue but depending on how much buffs you allow on a unique bufflist this problem may occure again. Test again with the shortcut bypasses and report back please. I'm looking forward for your feedback.

**Comment by dEROZA** [comment]
Ok. I can do it later, my PC's broken. Maybe I can reply to u in May.

**Comment by dEROZA** [comment]
2015 7:04:17 PM com.l2jserver.gameserver.network.serverpackets.AbstractHtmlPacket setHtml
WARNING: Html is too long! this will crash the client!
java.lang.Throwable
    at com.l2jserver.gameserver.network.serverpackets.AbstractHtmlPacket.setHtml(AbstractHtmlPacket.java:80)
    at com.l2jserver.gameserver.network.serverpackets.AbstractHtmlPacket.<init>(AbstractHtmlPacket.java:68)
    at com.l2jserver.gameserver.network.serverpackets.NpcHtmlMessage.<init>(NpcHtmlMessage.java:50)
    at YANModPack.src.YANModScript.showAdvancedHtml(YANModScript.java:130)
    at YANModPack.YANBuffer.src.YANBuffer._showAdvancedHtml(YANBuffer.java:126)
    at YANModPack.YANBuffer.src.YANBuffer._htmlShowUnique(YANBuffer.java:207)
    at YANModPack.YANBuffer.src.YANBuffer.executeHtmlCommand(YANBuffer.java:637)
    at YANModPack.src.YANModScript.executeCommand(YANModScript.java:208)
    at YANModPack.YANBuffer.src.YANBufferBypassHandler.useBypass(YANBufferBypassHandler.java:58)
    at com.l2jserver.gameserver.network.clientpackets.RequestBypassToServer.runImpl(RequestBypassToServer.java:338)
    at com.l2jserver.gameserver.network.clientpackets.L2GameClientPacket.run(L2GameClientPacket.java:70)
    at com.l2jserver.gameserver.network.L2GameClient.run(L2GameClient.java:1134)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)

**Comment by dEROZA** [comment]
Can you great pagination method?!
Example: << page1, page2 ... lastPage >>

**Comment by HorridoJoho** [comment]
This problem is next on my list. I have no ETA tho.
